apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-demo
  labels:
   app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
     app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
       containers:
       - name: nginx
         image: nginx:1.14.1
         ports:
         - containerPort: 80


  # kubectl apply -f deployment.yaml
  # kubectl get deployment
  # kubectl get deployment -o wide
  # kubectl describe deployment <deploy-name>
  
