
apiVersion: v1
kind: ReplicationController
metadata:
 name: rc-demo

spec:
  replicas: 3
  selector:
   app: nginx-app

template:
  metadata:
   labels:
    app: nginx-app

  spec:
    containers:
    - name: nginx-app
      image: nginx
      ports:
      - containerPort: 80

